### ISSUE TITLE
Q: multiline support?

### ISSUE THREAD

**Issue by gcb** [dead-claudia/journald-exporter#23]
Does it support multiline, but concatenating _STREAM_ID et al into the same event?

did not find anything from code search

thank you!

**Comment by dead-claudia** [comment]
@gcb I use libsystemd's `sd_journal_*` functions to read the journal, so yes, multiline messages are only counted as single messages in the metrics.

However, message *entries* in a given journal entry after the first are dropped, because I use `sd_journal_get_data` to get decoded values. (I have perf concerns with libsystemd's journal entry field iterator implementation as it allocates a lot.)

So as long as your multi-line message is contained within a single field, you're good. Just don't add multiple fields ([systemd's docs warn of the risks](https://www.freedesktop.org/software/systemd/man/latest/systemd.journal-fields.html#)) in a single `sd_journal_send` call, and message sizes will get counted correctly.

**Comment by gcb** [comment]
Thank you. I actually had misread that page you linked at some point.

For some reason I was implementing on my side expecting multiple MESSAGE thinking that was the hack for multi-line. No idea how i read that so wrong, since MESSAGE is the one they implore to never use multiple times.

It appears the only exception is `_UDEV_DEVLINK` on the default set.
